spring:
  cache:
    type: simple
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  jpa:
    show-sql: true

management:
  health:
    redis:
      enabled: false

logging:
  level:
    com.pgsc.tracko: DEBUG
    org.hibernate.SQL: DEBUG
